TOKEN_TYPES = [
    # single-character tokens
    "LEFT_PAREN",
    "RIGHT_PAREN",
    "LEFT_BRACE",
    "RIGHT_BRACE",
    "LEFT_BRACKET",
    "RIGHT_BRACKET",
    "COMMA",
    "DOT",
    "MINUS",
    "PLUS",
    "SEMICOLON",
    "SLASH",
    "STAR",

    # one or two character tokens
    "BANG",
    "BANG_EQUAL",
    "EQUAL",
    "EQUAL_EQUAL",
    "GREATER",
    "GREATER_EQUAL",
    "LESS",
    "LESS_EQUAL",

    # literals
    "IDENTIFIER",
    "STRING",
    "NUMBER",

    # keywords
    "AND",
    "CLASS",
    "ELSE",
    "FALSE",
    "FUN",
    "FOR",
    "IF",
    "NIL",
    "OR",
    "PRINT",
    "RETURN",
    "SUPER",
    "THIS",
    "TRUE",
    "VAR",
    "WHILE",

    "EOF",
]

if __name__ == "__main__":
    with open("lox/token_type.py", "w+") as f:
        f.write("# Auto-generated by tool/token_type_enum.py\n")
        f.write("# (because actual Python enums stink)\n\n")

        for i, token_type in enumerate(TOKEN_TYPES):
            f.write(f"{token_type} = {i}\n")
